name: Add Labels
on:
  pull_request:
    types: [opened, edited, synchronize, review_requested, ready_for_review, labeled, unlabeled]
  issue_comment:
      types: [created]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1.1.0
        if: contains(github.event.pull_request.body, 'mejora')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            documentation
            changelog
            enhancement